spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres-payments-gama:5433/db_payments?useSSL=false
    username: fazt2
    password: 123456
  kafka:
    bootstrap-servers: kafka-1-gama:9090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
        allow.auto.create.topics: false
    consumer:
      group-id: payments-ms-angieBraids
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'pe.com.gamacommerce.*'
        allow.auto.create.topics: false
    admin:
      auto-create: false

payments:
  commands:
    topic:
      name: payments-commands
  events:
    topic:
      name: payments-events
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service-gama:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 8086

springdoc:
  api-docs:
    enabled: true
    path: /v1/payment-service/v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    path: /v1/payment-service/swagger-ui.html

stripe:
  secret:
    key: sk_test_51SdYNAHMrevbTo0hluIqJLsFsNxAbxOYy4qQquw6LvsTmKsiK13jSLUdf6ExMeCqMlQAKXx6Jz4iDKF134NB5Jh8007xjKWxWe
  publishable:
    key: pk_test_51SdYNAHMrevbTo0hB34XndyOb0O80ZOJXhsRTJlYKKkVnS4s1U4ZkWZV8H0eMPaJLENRpkQ76Qt7jANtFyzRtI0200LaYgs2k7
  currency: pen
  webhook:
    secret: whsec_06e4671138f44db80c6b6a6ec8c72dcf4b2771776f828106d1bc2f65aec7e611
    
STRIPE_PUBLISHABLE_KEY: pk_test_51SdYNAHMrevbTo0hB34XndyOb0O80ZOJXhsRTJlYKKkVnS4s1U4ZkWZV8H0eMPaJLENRpkQ76Qt7jANtFyzRtI0200LaYgs2k7
