server:
  port: 0 # Set to 0 to let the system choose a random port

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql-users-gama.cazmyuk06u4q.us-east-1.rds.amazonaws.com:3308/db_users
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service-gama:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
token:
  sunat:
    api: sk_6846.u6J68fUYxblntyDPveU5HB5rQY2WNxdy
    
BUCKET_NAME_USUARIOS: gamacommerce-images-dev
BUCKET_USUARIOS_CLIENT_ID: AKIA2JNK5BVLHBIYE4J2
BUCKET_USUARIOS_SECRET_KEY: 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
AWS_S3_REGION: us-east-1
